
version: '3'

services:
  cups-api:
    build: .    
    image: yixing/cups-api 
    container_name: cups-api    
    network_mode: host         
    restart: on-failure:5
    volumes:
      - ./temp:/code/temp
      - ./conf:/code/conf
    environment:
      - CUPS_CONFIG_FILE=conf/cups_client.yaml